name: cmangos
services:
  mariadb:
    image: mariadb:11.5
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_SUPERPASS}"

    networks:
      - default

    volumes:
      - mariadb_data:/var/lib/mysql
      - ./database:/etc/mysql/conf.d:ro

  mangosd:
    image: "ghcr.io/byloth/cmangos/${WOW_VERSION}:latest"
    depends_on:
      - mariadb

    environment:
      MANGOS_DBHOST: mariadb
      MANGOS_DBUSER: "${MANGOS_DBUSER}"
      MANGOS_DBPASS: "${MANGOS_DBPASS}"
      TZ: "${WOW_TIMEZONE}"

    command: mangosd
    stdin_open: true
    tty: true
    networks:
      - default

    ports:
      - "${MANGOSD_PORT:-8085}:8085"

    volumes:
      - cmangos_mangosd_data:/var/lib/mangos:ro
      - ./runner/config:/opt/mangos/conf:ro

  realmd:
    image: "ghcr.io/byloth/cmangos/${WOW_VERSION}:latest"
    depends_on:
      - mariadb

    environment:
      MANGOS_DBHOST: mariadb
      MANGOS_DBUSER: "${MANGOS_DBUSER}"
      MANGOS_DBPASS: "${MANGOS_DBPASS}"
      TZ: "${WOW_TIMEZONE}"

    command: realmd
    networks:
      - default

    ports:
      - "${REALMD_PORT:-3724}:3724"

    volumes:
      - cmangos_mangosd_data:/var/lib/mangos:ro

  phpmyadmin:
    image: phpmyadmin:5.2
    depends_on:
      - mariadb

    profiles:
      - debug

    environment:
      PMA_HOST: mariadb
      PMA_USER: root
      PMA_PASSWORD: "${MYSQL_SUPERPASS}"

    networks:
      - default

    ports:
      - "${PHPMYADMIN_PORT:-8080}:80"

networks:
  default:

volumes:
  mariadb_data:
  cmangos_mangosd_data:
    external: true
