version: "3.9"
services:
  mariadb:
    image: mariadb:10.3
    environment:
      MYSQL_ROOT_PASSWORD: root00

    networks:
      - default

    ports:
      - 3306:3306

    volumes:
      - ./mariadb_data:/var/lib/mysql

  # mangosd:
  #   image: cmangos/runner:tbc
  #   depends_on:
  #     - mariadb

  #   environment:
  #     CMANGOS_DBHOST: "172.17.0.1"
  #     CMANGOS_DBUSER: mangos
  #     CMANGOS_DBPASS: mangos00

  #   command: mangosd
  #   networks:
  #     - default
  #     - exposed

  #   ports:
  #     - 8085:8085

  #   volumes:
  #     - ./mangosd_data/Cameras:/opt/mangos/data/Cameras:ro
  #     - ./mangosd_data/dbc:/opt/mangos/data/dbc:ro
  #     - ./mangosd_data/maps:/opt/mangos/data/maps:ro
  #     - ./mangosd_data/mmaps:/opt/mangos/data/mmaps:ro
  #     - ./mangosd_data/vmaps:/opt/mangos/data/vmaps:ro

  # realmd:
  #   image: cmangos/runner:tbc
  #   depends_on:
  #     - mariadb

  #   environment:
  #     CMANGOS_DBHOST: "172.17.0.1"
  #     CMANGOS_DBUSER: mangos
  #     CMANGOS_DBPASS: mangos00

  #   command: realmd
  #   networks:
  #     - default
  #     - exposed

  #   ports:
  #     - 3724:3724

  phpmyadmin:
    image: phpmyadmin:5.1
    depends_on:
      - mariadb

    environment:
      PMA_HOST: mariadb
      PMA_USER: root
      PMA_PASSWORD: root00

    networks:
      - default
      - exposed

    ports:
      - 8080:80

networks:
  default:
  exposed:
    external: true
