name: cmangos
version: "3.9"
services:
  mariadb:
    image: mariadb:10.10
    environment:
      MYSQL_ROOT_PASSWORD: root00

    networks:
      - default

    ports:
      - "3306:3306"

    volumes:
      - mariadb_data:/var/lib/mysql
      - ./database:/etc/mysql/conf.d:ro

    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      retries: 10
      timeout: 20s

  mangosd:
    image: ghcr.io/byloth/cmangos/tbc:latest
    depends_on:
      mariadb:
        condition: service_healthy

    environment:
      MANGOS_DBHOST: mariadb
      MANGOS_DBUSER: mangos
      MANGOS_DBPASS: mangos00

    command: mangosd
    stdin_open: true
    tty: true
    networks:
      - default

    ports:
      - "8085:8085"

    volumes:
      - mangosd_data:/var/lib/mangos:ro
      - ./runner/config:/opt/mangos/conf:ro

  realmd:
    image: ghcr.io/byloth/cmangos/tbc:latest
    depends_on:
      mariadb:
        condition: service_healthy

    environment:
      MANGOS_DBHOST: mariadb
      MANGOS_DBUSER: mangos
      MANGOS_DBPASS: mangos00

    command: realmd
    networks:
      - default

    ports:
      - "3724:3724"

  phpmyadmin:
    image: phpmyadmin:5.2
    depends_on:
      - mariadb

    profiles:
      - debug

    environment:
      PMA_HOST: mariadb
      PMA_USER: root
      PMA_PASSWORD: root00

    networks:
      - default

    ports:
      - "8080:80"

networks:
  default:

volumes:
  mariadb_data:
  mangosd_data:
