###############################################
#  CMaNGOS AI Playerbot - Configuration file  #
###############################################

AiPlayerbot.Enabled = 1

# https://github.com/cmangos/issues/issues/3912
AiPlayerbot.RandomBotAutologin = 0
