name: Classic
on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * *'

jobs:
  build-classic:
    name: Classic
    uses: ./.github/workflows/template.yml
    with:
      expansion: classic
