name: Docker images build & release
on:
  push:
  workflow_dispatch:

jobs:
  builder-build:
    name: "`builder` building process"
    runs-on: ubuntu-latest
    steps:
      - name: Clone the repository
        uses: actions/checkout@v2
      - name: Configure the Docker environment
        uses: Byloth/docker-setup-action@v1
        with:
          registry: ghcr.io

      - name: Login to the GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Definition of environmental variables
        run: |
          echo BUILDER_IMAGE_REF="${{ env.DOCKER_IMAGE }}/builder:${{ env.GITHUB_SHORT_SHA }}" >> "${GITHUB_ENV}" && \
          echo BUILDER_IMAGE_TAG="${{ env.DOCKER_IMAGE }}/builder:${{ env.GITHUB_REF_SLUG }}" >> "${GITHUB_ENV}" && \
          \
          echo BUILDER_IMAGE_CACHE="${{ env.DOCKER_IMAGE }}/builder:cache" >> "${GITHUB_ENV}"

      - name: Pull the Docker cache images
        run: |
          if docker pull "${{ env.BUILDER_IMAGE_REF }}"
          then
            docker tag "${{ env.BUILDER_IMAGE_REF }}" "${{ env.BUILDER_IMAGE_CACHE }}"

          elif docker pull "${{ env.BUILDER_IMAGE_TAG }}"
          then
            docker tag "${{ env.BUILDER_IMAGE_TAG }}" "${{ env.BUILDER_IMAGE_CACHE }}"
          fi

      - name: Build the Docker images
        run: |
          docker build --build-arg THREADS="2" \
                       --cache-from "${{ env.BUILDER_IMAGE_CACHE }}" \
                       --tag "${{ env.BUILDER_IMAGE_REF }}" \
                       --tag "${{ env.BUILDER_IMAGE_TAG }}" \
            \
            ./builder/

      - name: Push the Docker images
        run: |
          docker push "${{ env.BUILDER_IMAGE_REF }}" && \
          docker push "${{ env.BUILDER_IMAGE_TAG }}"

  runner-build:
    name: "`runner` building process"
    needs: builder-build
    runs-on: ubuntu-latest
    steps:
      - name: Clone the repository
        uses: actions/checkout@v2
      - name: Configure the Docker environment
        uses: Byloth/docker-setup-action@v1
        with:
          registry: ghcr.io

      - name: Login to the GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Definition of environmental variables
        run: |
          echo BUILDER_IMAGE="${{ env.DOCKER_IMAGE }}/builder:${{ env.GITHUB_SHORT_SHA }}" >> "${GITHUB_ENV}" && \
          \
          echo RUNNER_IMAGE_REF="${{ env.DOCKER_IMAGE }}/runner:${{ env.GITHUB_SHORT_SHA }}" >> "${GITHUB_ENV}" && \
          echo RUNNER_IMAGE_TAG="${{ env.DOCKER_IMAGE }}/runner:${{ env.GITHUB_REF_SLUG }}" >> "${GITHUB_ENV}" && \
          \
          echo RUNNER_IMAGE_CACHE="${{ env.DOCKER_IMAGE }}/runner:cache" >> "${GITHUB_ENV}"

      - name: Pull the CMaNGOS builder image
        run: |
          docker pull "${{ env.BUILDER_IMAGE }}" && \
          docker tag "${{ env.BUILDER_IMAGE }}" "cmangos/builder:tbc"

      - name: Pull the Docker cache images
        run: |
          if docker pull "${{ env.RUNNER_IMAGE_REF }}"
          then
            docker tag "${{ env.RUNNER_IMAGE_REF }}" "${{ env.RUNNER_IMAGE_CACHE }}"

          elif docker pull "${{ env.RUNNER_IMAGE_TAG }}"
          then
            docker tag "${{ env.RUNNER_IMAGE_TAG }}" "${{ env.RUNNER_IMAGE_CACHE }}"
          fi

      - name: Build the Docker images
        run: |
          docker build --cache-from "${{ env.RUNNER_IMAGE_CACHE }}" \
                       --tag "${{ env.RUNNER_IMAGE_REF }}" \
                       --tag "${{ env.RUNNER_IMAGE_TAG }}" \
            \
            ./runner/

      - name: Push the Docker images
        run: |
          docker push "${{ env.DOCKER_IMAGE }}/runner:${{ env.GITHUB_REF_SLUG }}" & \
          docker push "${{ env.DOCKER_IMAGE }}/runner:${{ env.GITHUB_SHORT_SHA }}"
