name: Build WotLK
on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '0 4 * * *'

jobs:
  build-wotlk:
    name: Build WotLK
    uses: ./.github/workflows/template.yml
    with:
      expansion: wotlk
