name: "<template>"
on:
  workflow_call:
    inputs:
      expansion:
        required: true
        type: string

jobs:
  build-builder:
    name: "Builder"
    runs-on: ubuntu-latest
    steps:
      - name: Clone the repository
        uses: actions/checkout@v3
      - name: Configure the Docker environment
        uses: Byloth/docker-setup-action@v1
        with:
          registry: ghcr.io
          repository: Byloth/CMaNGOS

      - name: Login to the GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Definition of environmental variables
        run: |
          echo BUILDER_IMAGE_REF="${{ env.DOCKER_IMAGE }}/${{ inputs.expansion }}/builder:${{ env.GITHUB_SHORT_SHA }}" \
            >> "${GITHUB_ENV}" && \
          echo BUILDER_IMAGE_TAG="${{ env.DOCKER_IMAGE }}/${{ inputs.expansion }}/builder:${{ env.GITHUB_REF_SLUG }}" \
            >> "${GITHUB_ENV}" && \
          \
          echo BUILDER_IMAGE_LATEST="${{ env.DOCKER_IMAGE }}/${{ inputs.expansion }}/builder:latest" >> "${GITHUB_ENV}" && \
          echo BUILDER_IMAGE_CACHE="${{ env.DOCKER_IMAGE }}/${{ inputs.expansion }}/builder:cache" >> "${GITHUB_ENV}"

      - name: Pull the Docker cache images
        run: |
          if docker pull "${{ env.BUILDER_IMAGE_REF }}"
          then
            docker tag "${{ env.BUILDER_IMAGE_REF }}" "${{ env.BUILDER_IMAGE_CACHE }}"

          elif docker pull "${{ env.BUILDER_IMAGE_TAG }}"
          then
            docker tag "${{ env.BUILDER_IMAGE_TAG }}" "${{ env.BUILDER_IMAGE_CACHE }}"
          
          elif docker pull "${{ env.BUILDER_IMAGE_LATEST }}"
          then
            docker tag "${{ env.BUILDER_IMAGE_LATEST }}" "${{ env.BUILDER_IMAGE_CACHE }}"
          fi

      - name: Definition of build arguments
        run: |
          echo MANGOS_SHA1="$(curl -sSL https://api.github.com/repos/cmangos/mangos-${{ inputs.expansion }}/commits/master \
                                   -H "Accept: application/vnd.github.VERSION.sha")" >> "${GITHUB_ENV}" && \
          echo DATABASE_SHA1="$(curl -sSL https://api.github.com/repos/cmangos/${{ inputs.expansion }}-db/commits/master \
                                     -H "Accept: application/vnd.github.VERSION.sha")" >> "${GITHUB_ENV}" && \
          \
          echo TIMESTAMP="$(date -u +"%Y-%m-%dT%H:%M:%SZ")" >> "${GITHUB_ENV}" && \
          echo VERSION_CODE="1.0.0-nightly+$(date -u +"%Y%m%d")" >> "${GITHUB_ENV}"

      - name: Build the Docker images
        run: |
          docker build --build-arg EXPANSION="${{ inputs.expansion }}" \
                       --build-arg MANGOS_SHA1="${{ env.MANGOS_SHA1 }}" \
                       --build-arg DATABASE_SHA1="${{ env.DATABASE_SHA1 }}" \
                       --build-arg THREADS="2" \
                       --build-arg COMMIT_SHA="${{ github.sha }}" \
                       --build-arg CREATE_DATE="${{ env.TIMESTAMP }}" \
                       --build-arg VERSION="${{ env.VERSION_CODE }}" \
                       --cache-from "${{ env.BUILDER_IMAGE_CACHE }}" \
                       --tag "${{ env.BUILDER_IMAGE_REF }}" \
                       --tag "${{ env.BUILDER_IMAGE_TAG }}" \
                       --target "builder" \
            \
            .

      - name: Push the Docker images
        run: |
          docker push "${{ env.BUILDER_IMAGE_REF }}" && \
          docker push "${{ env.BUILDER_IMAGE_TAG }}"

      - name: Push latest Docker image
        if: ${{ github.ref == 'refs/heads/master' }}
        run: |
          docker tag "${{ env.BUILDER_IMAGE_REF }}" "${{ env.BUILDER_IMAGE_LATEST }}" && \
          docker push "${{ env.BUILDER_IMAGE_LATEST }}"

  build-runner:
    name: "Runner"
    needs: build-builder
    runs-on: ubuntu-latest
    steps:
      - name: Clone the repository
        uses: actions/checkout@v3
      - name: Configure the Docker environment
        uses: Byloth/docker-setup-action@v1
        with:
          registry: ghcr.io
          repository: Byloth/CMaNGOS

      - name: Login to the GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Definition of environmental variables
        run: |
          echo BUILDER_IMAGE="${{ env.DOCKER_IMAGE }}/${{ inputs.expansion }}/builder:${{ env.GITHUB_SHORT_SHA }}" \
            >> "${GITHUB_ENV}" && \
          \
          echo RUNNER_IMAGE_REF="${{ env.DOCKER_IMAGE }}/${{ inputs.expansion }}:${{ env.GITHUB_SHORT_SHA }}" \
            >> "${GITHUB_ENV}" && \
          echo RUNNER_IMAGE_TAG="${{ env.DOCKER_IMAGE }}/${{ inputs.expansion }}:${{ env.GITHUB_REF_SLUG }}" \
            >> "${GITHUB_ENV}" && \
          \
          echo RUNNER_IMAGE_LATEST="${{ env.DOCKER_IMAGE }}/${{ inputs.expansion }}:latest" >> "${GITHUB_ENV}" && \
          echo RUNNER_IMAGE_CACHE="${{ env.DOCKER_IMAGE }}/${{ inputs.expansion }}:cache" >> "${GITHUB_ENV}"

      - name: Pull the CMaNGOS builder image
        run: docker pull "${{ env.BUILDER_IMAGE }}"

      - name: Pull the Docker cache images
        run: |
          if docker pull "${{ env.RUNNER_IMAGE_REF }}"
          then
            docker tag "${{ env.RUNNER_IMAGE_REF }}" "${{ env.RUNNER_IMAGE_CACHE }}"

          elif docker pull "${{ env.RUNNER_IMAGE_TAG }}"
          then
            docker tag "${{ env.RUNNER_IMAGE_TAG }}" "${{ env.RUNNER_IMAGE_CACHE }}"
          
          elif docker pull "${{ env.RUNNER_IMAGE_LATEST }}"
          then
            docker tag "${{ env.RUNNER_IMAGE_LATEST }}" "${{ env.RUNNER_IMAGE_CACHE }}"
          fi

      - name: Definition of build arguments
        run: |
          echo MANGOS_SHA1="$(curl -sSL https://api.github.com/repos/cmangos/mangos-${{ inputs.expansion }}/commits/master \
                                   -H "Accept: application/vnd.github.VERSION.sha")" >> "${GITHUB_ENV}" && \
          echo DATABASE_SHA1="$(curl -sSL https://api.github.com/repos/cmangos/${{ inputs.expansion }}-db/commits/master \
                                     -H "Accept: application/vnd.github.VERSION.sha")" >> "${GITHUB_ENV}" && \
          \
          echo TIMESTAMP="$(date -u +"%Y-%m-%dT%H:%M:%SZ")" >> "${GITHUB_ENV}" && \
          echo VERSION_CODE="1.0.0-nightly+$(date -u +"%Y%m%d")" >> "${GITHUB_ENV}"

      - name: Build the Docker images
        run: |
          docker build --build-arg EXPANSION="${{ inputs.expansion }}" \
                       --build-arg MANGOS_SHA1="${{ env.MANGOS_SHA1 }}" \
                       --build-arg DATABASE_SHA1="${{ env.DATABASE_SHA1 }}" \
                       --build-arg THREADS="2" \
                       --build-arg COMMIT_SHA="${{ github.sha }}" \
                       --build-arg CREATE_DATE="${{ env.TIMESTAMP }}" \
                       --build-arg VERSION="${{ env.VERSION_CODE }}" \
                       --cache-from "${{ env.BUILDER_IMAGE }}" \
                       --cache-from "${{ env.RUNNER_IMAGE_CACHE }}" \
                       --tag "${{ env.RUNNER_IMAGE_REF }}" \
                       --tag "${{ env.RUNNER_IMAGE_TAG }}" \
                       --target "runner" \
            \
            .

      - name: Push the Docker images
        run: |
          docker push "${{ env.RUNNER_IMAGE_REF }}" & \
          docker push "${{ env.RUNNER_IMAGE_TAG }}"

      - name: Push latest Docker image
        if: ${{ github.ref == 'refs/heads/master' }}
        run: |
          docker tag "${{ env.RUNNER_IMAGE_REF }}" "${{ env.RUNNER_IMAGE_LATEST }}" && \
          docker push "${{ env.RUNNER_IMAGE_LATEST }}"
